// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using crud_chat.Models;

namespace crud_chat.Migrations
{
    [DbContext(typeof(CrudChatContext))]
    [Migration("20200301182042_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2");

            modelBuilder.Entity("crud_chat.Models.Message", b =>
                {
                    b.Property<long>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("TEXT");

                    b.HasKey("MessageId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("crud_chat.Models.Room", b =>
                {
                    b.Property<long>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("crud_chat.Models.RoomMessages", b =>
                {
                    b.Property<long>("RoomMessagesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("MessageId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoomId")
                        .HasColumnType("INTEGER");

                    b.HasKey("RoomMessagesId");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomMessages");
                });

            modelBuilder.Entity("crud_chat.Models.Sphere", b =>
                {
                    b.Property<long>("SphereId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("SphereId");

                    b.ToTable("Spheres");
                });

            modelBuilder.Entity("crud_chat.Models.SphereRooms", b =>
                {
                    b.Property<long>("SphereRoomsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SphereId")
                        .HasColumnType("INTEGER");

                    b.HasKey("SphereRoomsId");

                    b.HasIndex("SphereId");

                    b.ToTable("SphereRooms");
                });

            modelBuilder.Entity("crud_chat.Models.RoomMessages", b =>
                {
                    b.HasOne("crud_chat.Models.Room", null)
                        .WithMany("Messages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("crud_chat.Models.SphereRooms", b =>
                {
                    b.HasOne("crud_chat.Models.Sphere", null)
                        .WithMany("Rooms")
                        .HasForeignKey("SphereId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
